# Imagen base de Node
FROM node:18-alpine

# Crear directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias (solo producción si quieres más liviano)
RUN npm install --omit=dev

# Copiar el resto del código
COPY . .

# Exponer el puerto (lo tomará del .env, pero aquí va fijo para Docker)
EXPOSE 8085

# Comando de inicio
CMD ["npm", "start"]
